#colors
SUCCESS='green'
FAILURE='red'
DEBUG='cyan'
RETRY='yellow'

TIMEOUT_PERIOD = 16
SYNCING_PERIOD = 8

ORIGIN_SERVERS_STORE_CREDENTIALS = [("localhost", 9999), ("localhost", 8999)]
ORIGIN_SERVERS_REQUEST_CREDENTIALS = [("localhost", 10000), ("localhost", 9000)]
SYNC_PORT_1 = 10001
SYNC_PORT_2 = 10002
NO_OF_ORIGIN_SERVERS = 2

EDGE_SERVERS_REQUEST_CREDENTIALS = [("localhost", 10005), ("localhost", 10006)]
NO_OF_EDGE_SERVERS = 2

FILE_FOUND = "FOUND"
FILE_NOT_FOUND = "NOTFOUND"
